name: flutter_module
description: "A new Flutter module project."
version: 1.0.0+1

environment:
  sdk: 3.4.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: 4.7.0
  datadog_flutter_plugin: 2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
  assets:
    - shorebird.yaml
